/**
 * 控制台内容种子数据
 * 规范：绝对禁止输出任何 Emoji 表情符号
 */

import type { Category, Tag, Post, Attachment, SiteSettings } from "./types";

export const DEFAULT_CATEGORIES: Category[] = [
    {
        id: "cat-examples",
        name: "示例",
        slug: "examples",
        description: "各类功能特性演示与 Markdown 排版范例",
        color: "#3b82f6",
        priority: 1,
        postCount: 5,
    },
    {
        id: "cat-guides",
        name: "向导",
        slug: "guides",
        description: "模板指南与全流程使用向导",
        color: "#10b981",
        priority: 2,
        postCount: 2,
    },
    {
        id: "cat-advanced-customization",
        name: "高级定制",
        slug: "advanced-customization",
        description: "进阶玩法、扩展插件与深度定制指南",
        color: "#8b5cf6",
        priority: 3,
        postCount: 1,
        parentId: "cat-guides",
    },
    {
        id: "cat-getting-started",
        name: "入门指南",
        slug: "getting-started",
        description: "快速上手与博客基础使用向导",
        color: "#f59e0b",
        priority: 4,
        postCount: 1,
        parentId: "cat-guides",
    },
];

export const DEFAULT_TAGS: Tag[] = [
    { id: "tag-copy-protection", name: "防拷", slug: "copy-protection", color: "#6366f1", postCount: 1 },
    { id: "tag-encryption", name: "加密", slug: "encryption", color: "#ec4899", postCount: 1 },
    { id: "tag-markdown", name: "折扣", slug: "markdown", color: "#10b981", postCount: 3 },
    { id: "tag-mermaid", name: "美人鱼", slug: "mermaid", color: "#06b6d4", postCount: 1 },
    { id: "tag-video", name: "视频", slug: "video", color: "#f97316", postCount: 1 },
];

export const DEFAULT_POSTS: Post[] = [
    {
        id: "post-getting-started",
        title: "Guide for Template - Getting Started",
        slug: "guide-getting-started",
        summary: "How to use this blog template.",
        content: `# Guide for Template - Getting Started\n\nTip: For the things that are not mentioned in this guide, you may find the answers in the Astro Docs.\n\n## Front-matter of Posts\n\n\`\`\`yaml\n---\ntitle: My First Blog Post\npublished: 2020-02-02\ndescription: This is the first post of my new Astro blog.\n\`\`\``,
        cover: "/_astro/Cover - Getting Started.CLLNYX7x_vs76V.webp",
        status: "published",
        visibility: "public",
        pinned: true,
        allowComment: true,
        categories: ["cat-guides", "cat-getting-started"],
        tags: [],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 1820,
        wordCount: 650,
        readingTime: 3,
        createdAt: "2001-10-02T00:00:00Z",
        updatedAt: "2001-10-02T00:00:00Z",
    },
    {
        id: "post-mermaid",
        title: "Mermaid Example",
        slug: "mermaids",
        summary: "A simple example of a Markdown blog post with Mermaid.",
        content: `# Complete Guide to Markdown with Mermaid Diagrams\n\nThis article demonstrates how to create various complex diagrams using Mermaid in Markdown documents, including flowcharts, sequence diagrams, Gantt charts, class diagrams, and state diagrams.`,
        cover: "https://picsum.photos/200/300?random=18",
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-markdown", "tag-mermaid"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 1240,
        wordCount: 420,
        readingTime: 2,
        createdAt: "2011-11-02T00:00:00Z",
        updatedAt: "2011-11-02T00:00:00Z",
    },
    {
        id: "post-encryption",
        title: "Encryption Example",
        slug: "encryption",
        summary: "Password: 123456",
        content: `# Password Protected Post\n\nThis is an example of a password-protected post in the mc00 theme. The content below is encrypted using AES and can only be viewed by entering the correct password.`,
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-encryption"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 980,
        wordCount: 310,
        readingTime: 2,
        createdAt: "2020-02-02T00:00:00Z",
        updatedAt: "2020-02-02T00:00:00Z",
    },
    {
        id: "post-video",
        title: "Video Example",
        slug: "videos",
        summary: "This post demonstrates how to embed video in a blog post.",
        content: `## Instructions\n\nJust copy the embed code from YouTube or other platforms, and paste it in the markdown file as below:\n\n\`\`\`yaml\n---\ntitle: Include Video in the Post\npublished: 2023-10-19\n\`\`\``,
        cover: "https://picsum.photos/200/300?random=22",
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-markdown", "tag-video"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 860,
        wordCount: 290,
        readingTime: 1,
        createdAt: "2021-12-02T00:00:00Z",
        updatedAt: "2021-12-02T00:00:00Z",
    },
    {
        id: "post-copy-protection",
        title: "Copy Protection Example",
        slug: "copy-protection",
        summary: "This post demonstrates the copyProtection frontmatter option with granular controls.",
        content: `# Post with Copy Protection Enabled\n\nThis post has all four copyProtection sub-options enabled in its frontmatter.`,
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-copy-protection"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 1120,
        wordCount: 380,
        readingTime: 2,
        createdAt: "2022-11-01T00:00:00Z",
        updatedAt: "2022-11-01T00:00:00Z",
    },
    {
        id: "post-advanced-customization",
        title: "Guide for Template - Advanced Customization",
        slug: "guide-advanced-customization",
        summary: "Master the advanced features and customization options of the mc00 template.",
        content: `# Guide for Template - Advanced Customization\n\nThis guide covers advanced customization options and features available in the mc00 template, from global configurations to specialized Markdown extensions.`,
        cover: "/_astro/Cover - Advanced Customization.BlPeYdZm_Z1PEq3k.webp",
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-guides", "cat-advanced-customization"],
        tags: [],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 1530,
        wordCount: 780,
        readingTime: 4,
        createdAt: "2024-02-10T00:00:00Z",
        updatedAt: "2024-02-10T00:00:00Z",
    },
    {
        id: "post-draft",
        title: "Draft Example",
        slug: "draft",
        summary: "This article is currently in a draft state and is not published.",
        content: `# This Article is a Draft\n\nThis article is currently in a draft state and is not published. Therefore, it will not be visible to the general audience.`,
        status: "draft",
        visibility: "private",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-markdown"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 0,
        wordCount: 150,
        readingTime: 1,
        createdAt: "2021-12-02T00:00:00Z",
        updatedAt: "2021-12-02T00:00:00Z",
    },
];

export const DEFAULT_ATTACHMENTS: Attachment[] = [
    {
        id: "att-1",
        name: "Cover - Getting Started.jpg",
        url: "/_astro/Cover - Getting Started.CLLNYX7x_vs76V.webp",
        size: 145280,
        type: "image/webp",
        uploadTime: "2026-04-01T10:15:00.000Z",
        uploaderId: "u-admin",
    },
    {
        id: "att-2",
        name: "Cover - Advanced Customization.jpg",
        url: "/_astro/Cover - Advanced Customization.BlPeYdZm_Z1PEq3k.webp",
        size: 204890,
        type: "image/webp",
        uploadTime: "2026-04-03T14:30:00.000Z",
        uploaderId: "u-admin",
    },
    {
        id: "att-3",
        name: "defaultWallpaper.jpg",
        url: "/assets/images/defaultWallpaper.jpg",
        size: 312500,
        type: "image/jpeg",
        uploadTime: "2026-04-05T09:40:00.000Z",
        uploaderId: "u-admin",
    },
];

export const DEFAULT_SETTINGS: SiteSettings = {
    siteName: "mc00",
    siteSubtitle: "Blog Template",
    announcement: "欢迎访问 mc00 博客管理控制台，全站支持液态玻璃与毛玻璃材质！",
    allowComments: true,
    copyProtection: false,
    enableRss: true,
    footerText: "© 2026 mc00. All Rights Reserved. / Powered by Twilight",
};
