/**
 * Halo 风格预置种子数据与 RBAC 规则字典
 * 规范：绝对禁止输出任何 Emoji 表情符号
 */

import type { Role, User, Category, Tag, Post, Attachment, SiteSettings, UserRole } from "./types";

export const DEFAULT_ROLES: Role[] = [
    {
        id: "admin",
        name: "超级管理员",
        description: "拥有系统全量控制权限，包括用户、角色、文章、系统设置与附件管理",
        isSystem: true,
        disallowAccessConsole: false,
        permissions: ["*"],
        badgeColor: "bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/30",
    },
    {
        id: "editor",
        name: "文章管理员",
        description: "管理所有文章、分类、标签与媒体资源，但无权修改系统设置和用户角色",
        isSystem: true,
        disallowAccessConsole: false,
        permissions: [
            "posts:*",
            "categories:*",
            "tags:*",
            "attachments:*",
            "view:public"
        ],
        badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/30",
    },
    {
        id: "author",
        name: "签约作者",
        description: "可创建与编辑属于自己的文章和草稿，上传个人素材，不可管理他人文章",
        isSystem: true,
        disallowAccessConsole: false,
        permissions: [
            "posts:create",
            "posts:edit:own",
            "posts:delete:own",
            "posts:publish",
            "attachments:*",
            "view:public"
        ],
        badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/30",
    },
    {
        id: "contributor",
        name: "投稿者",
        description: "可提交文章草稿，但无法直接公开上线，需管理员审核",
        isSystem: true,
        disallowAccessConsole: false,
        permissions: [
            "posts:create",
            "posts:edit:own",
            "attachments:*",
            "view:public"
        ],
        badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30",
    },
    {
        id: "reader",
        name: "访客读者",
        description: "普通浏览读者，仅拥有前台浏览与个人中心资料查看权限，禁止访问后台控制台",
        isSystem: true,
        disallowAccessConsole: true,
        permissions: ["view:public"],
        badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
    },
];

export const ROLE_INFO: Record<UserRole, { label: string; desc: string; badgeColor: string }> = {
    admin: {
        label: "超级管理员",
        desc: "系统全量控制权限",
        badgeColor: "bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/30",
    },
    editor: {
        label: "文章管理员",
        desc: "文章与内容全量管理",
        badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/30",
    },
    author: {
        label: "签约作者",
        desc: "仅管理本人创作内容",
        badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/30",
    },
    contributor: {
        label: "投稿撰稿人",
        desc: "提交初稿与排版",
        badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30",
    },
    reader: {
        label: "普通读者",
        desc: "仅前台阅读与个人资料",
        badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
    },
};

export const DEFAULT_USERS: User[] = [
    {
        id: "u-admin",
        username: "admin",
        name: "Halo 管理员",
        displayName: "Halo 管理员",
        email: "admin@mc00blog.local",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=HaloAdmin",
        role: "admin",
        bio: "博客主站超级管理员，负责全站架构、用户权限与内容总编审。",
        createdAt: "2026-01-01T08:00:00.000Z",
        status: "active",
    },
    {
        id: "u-editor",
        username: "editor_alex",
        name: "内容主管 Alex",
        displayName: "内容主管 Alex",
        email: "alex@mc00blog.local",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=AlexEditor",
        role: "editor",
        bio: "负责文章栏目策划、分类流转与高质量稿件校对。",
        createdAt: "2026-02-15T09:30:00.000Z",
        status: "active",
    },
    {
        id: "u-author",
        username: "author_tom",
        name: "签约专栏作家 Tom",
        displayName: "签约专栏作家 Tom",
        email: "tom@mc00blog.local",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=TomAuthor",
        role: "author",
        bio: "专注于 Astro 现代前端技术与全栈工程架构探索。",
        createdAt: "2026-03-01T14:20:00.000Z",
        status: "active",
    },
    {
        id: "u-contributor",
        username: "writer_lucy",
        name: "投稿人 Lucy",
        displayName: "投稿人 Lucy",
        email: "lucy@mc00blog.local",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=LucyWriter",
        role: "contributor",
        bio: "热爱分享开源心得与设计美学。",
        createdAt: "2026-03-20T11:10:00.000Z",
        status: "active",
    },
    {
        id: "u-reader",
        username: "reader_bob",
        name: "读者 Bob",
        displayName: "读者 Bob",
        email: "bob@mc00blog.local",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=BobReader",
        role: "reader",
        bio: "普通读者账号，用于测试非授权用户拦截。",
        createdAt: "2026-04-05T16:00:00.000Z",
        status: "active",
    },
];

export const DEFAULT_CATEGORIES: Category[] = [
    {
        id: "cat-examples",
        name: "示例",
        slug: "examples",
        description: "各类功能特性演示与 Markdown 排版范例",
        color: "#3b82f6",
        priority: 1,
        postCount: 5,
    },
    {
        id: "cat-guides",
        name: "向导",
        slug: "guides",
        description: "模板指南与全流程使用向导",
        color: "#10b981",
        priority: 2,
        postCount: 2,
    },
    {
        id: "cat-advanced-customization",
        name: "高级定制",
        slug: "advanced-customization",
        description: "进阶玩法、扩展插件与深度定制指南",
        color: "#8b5cf6",
        priority: 3,
        postCount: 1,
        parentId: "cat-guides",
    },
    {
        id: "cat-getting-started",
        name: "入门指南",
        slug: "getting-started",
        description: "快速上手与博客基础使用向导",
        color: "#f59e0b",
        priority: 4,
        postCount: 1,
        parentId: "cat-guides",
    },
];

export const DEFAULT_TAGS: Tag[] = [
    { id: "tag-copy-protection", name: "防拷", slug: "copy-protection", color: "#6366f1", postCount: 1 },
    { id: "tag-encryption", name: "加密", slug: "encryption", color: "#ec4899", postCount: 1 },
    { id: "tag-markdown", name: "折扣", slug: "markdown", color: "#10b981", postCount: 3 },
    { id: "tag-mermaid", name: "美人鱼", slug: "mermaid", color: "#06b6d4", postCount: 1 },
    { id: "tag-video", name: "视频", slug: "video", color: "#f97316", postCount: 1 },
];

export const DEFAULT_POSTS: Post[] = [
    {
        id: "post-getting-started",
        title: "Guide for Template - Getting Started",
        slug: "guide-getting-started",
        summary: "How to use this blog template.",
        content: `# Guide for Template - Getting Started\n\nTip: For the things that are not mentioned in this guide, you may find the answers in the Astro Docs.\n\n## Front-matter of Posts\n\n\`\`\`yaml\n---\ntitle: My First Blog Post\npublished: 2020-02-02\ndescription: This is the first post of my new Astro blog.\n\`\`\``,
        cover: "/_astro/Cover - Getting Started.CLLNYX7x_vs76V.webp",
        status: "published",
        visibility: "public",
        pinned: true,
        allowComment: true,
        categories: ["cat-guides", "cat-getting-started"],
        tags: [],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 1820,
        wordCount: 650,
        readingTime: 3,
        createdAt: "2001-10-02T00:00:00Z",
        updatedAt: "2001-10-02T00:00:00Z",
    },
    {
        id: "post-mermaid",
        title: "Mermaid Example",
        slug: "mermaids",
        summary: "A simple example of a Markdown blog post with Mermaid.",
        content: `# Complete Guide to Markdown with Mermaid Diagrams\n\nThis article demonstrates how to create various complex diagrams using Mermaid in Markdown documents, including flowcharts, sequence diagrams, Gantt charts, class diagrams, and state diagrams.`,
        cover: "https://picsum.photos/200/300?random=18",
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-markdown", "tag-mermaid"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 1240,
        wordCount: 420,
        readingTime: 2,
        createdAt: "2011-11-02T00:00:00Z",
        updatedAt: "2011-11-02T00:00:00Z",
    },
    {
        id: "post-encryption",
        title: "Encryption Example",
        slug: "encryption",
        summary: "Password: 123456",
        content: `# Password Protected Post\n\nThis is an example of a password-protected post in the mc00 theme. The content below is encrypted using AES and can only be viewed by entering the correct password.`,
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-encryption"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 980,
        wordCount: 310,
        readingTime: 2,
        createdAt: "2020-02-02T00:00:00Z",
        updatedAt: "2020-02-02T00:00:00Z",
    },
    {
        id: "post-video",
        title: "Video Example",
        slug: "videos",
        summary: "This post demonstrates how to embed video in a blog post.",
        content: `## Instructions\n\nJust copy the embed code from YouTube or other platforms, and paste it in the markdown file as below:\n\n\`\`\`yaml\n---\ntitle: Include Video in the Post\npublished: 2023-10-19\n\`\`\``,
        cover: "https://picsum.photos/200/300?random=22",
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-markdown", "tag-video"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 860,
        wordCount: 290,
        readingTime: 1,
        createdAt: "2021-12-02T00:00:00Z",
        updatedAt: "2021-12-02T00:00:00Z",
    },
    {
        id: "post-copy-protection",
        title: "Copy Protection Example",
        slug: "copy-protection",
        summary: "This post demonstrates the copyProtection frontmatter option with granular controls.",
        content: `# Post with Copy Protection Enabled\n\nThis post has all four copyProtection sub-options enabled in its frontmatter.`,
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-copy-protection"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 1120,
        wordCount: 380,
        readingTime: 2,
        createdAt: "2022-11-01T00:00:00Z",
        updatedAt: "2022-11-01T00:00:00Z",
    },
    {
        id: "post-advanced-customization",
        title: "Guide for Template - Advanced Customization",
        slug: "guide-advanced-customization",
        summary: "Master the advanced features and customization options of the mc00 template.",
        content: `# Guide for Template - Advanced Customization\n\nThis guide covers advanced customization options and features available in the mc00 template, from global configurations to specialized Markdown extensions.`,
        cover: "/_astro/Cover - Advanced Customization.BlPeYdZm_Z1PEq3k.webp",
        status: "published",
        visibility: "public",
        pinned: false,
        allowComment: true,
        categories: ["cat-guides", "cat-advanced-customization"],
        tags: [],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 1530,
        wordCount: 780,
        readingTime: 4,
        createdAt: "2024-02-10T00:00:00Z",
        updatedAt: "2024-02-10T00:00:00Z",
    },
    {
        id: "post-draft",
        title: "Draft Example",
        slug: "draft",
        summary: "This article is currently in a draft state and is not published.",
        content: `# This Article is a Draft\n\nThis article is currently in a draft state and is not published. Therefore, it will not be visible to the general audience.`,
        status: "draft",
        visibility: "private",
        pinned: false,
        allowComment: true,
        categories: ["cat-examples"],
        tags: ["tag-markdown"],
        authorId: "u-admin",
        authorName: "Halo 管理员",
        views: 0,
        wordCount: 150,
        readingTime: 1,
        createdAt: "2021-12-02T00:00:00Z",
        updatedAt: "2021-12-02T00:00:00Z",
    },
];

export const DEFAULT_ATTACHMENTS: Attachment[] = [
    {
        id: "att-1",
        name: "Cover - Getting Started.jpg",
        url: "/_astro/Cover - Getting Started.CLLNYX7x_vs76V.webp",
        size: 145280,
        type: "image/webp",
        uploadTime: "2026-04-01T10:15:00.000Z",
        uploaderId: "u-admin",
    },
    {
        id: "att-2",
        name: "Cover - Advanced Customization.jpg",
        url: "/_astro/Cover - Advanced Customization.BlPeYdZm_Z1PEq3k.webp",
        size: 204890,
        type: "image/webp",
        uploadTime: "2026-04-03T14:30:00.000Z",
        uploaderId: "u-admin",
    },
    {
        id: "att-3",
        name: "defaultWallpaper.jpg",
        url: "/assets/images/defaultWallpaper.jpg",
        size: 312500,
        type: "image/jpeg",
        uploadTime: "2026-04-05T09:40:00.000Z",
        uploaderId: "u-admin",
    },
];

export const DEFAULT_SETTINGS: SiteSettings = {
    siteName: "mc00",
    siteSubtitle: "Blog Template",
    announcement: "欢迎访问 mc00 博客管理控制台，全站支持液态玻璃与毛玻璃材质！",
    allowRegistration: false,
    allowComments: true,
    copyProtection: false,
    enableRss: true,
    footerText: "© 2026 mc00. All Rights Reserved. / Powered by Twilight",
};
